### ISSUE TITLE
Probleme quand les nouveaux nés arrivent au tour ou les valeurs tournent

### ISSUE THREAD

**Issue by Insoleet** [libre-money-projects/Geconomicus#34]
Pendant les RML7, nous avons rencontré un "bug" : si un joueur né le tour ou les valeurs tournent, il perd tout ce qu'il a, et au lieu d'avoir 4 valeurs en main, il n'a plus rien.

**Comment by galuel** [comment]
Les valeurs basses sont remplacées. Il suffit donc de les remplacer. Dès lors personne ne doit avoir "rien" : http://geconomicus.glibre.org/rules.html#but-du-jeu

**Comment by Insoleet** [comment]
>  la valeur en attente entre en jeu à ce moment là, et les valeurs basses sont retirées du jeu

Il faudrait éclaircir cette phrase et expliquer ce qui est réalisé alors. Ce n'est pas aussi clairement exprimé !

**Comment by galuel** [comment]
Oui, il faut encore éclaircir des points, simplifier, clarifier, encore et toujours !

**Comment by galuel** [comment]
Solved in 2.13 version
