### ISSUE TITLE
Logo du menu invisible sous Firefox Linux

### ISSUE THREAD

**Issue by blavenie** [libre-money-projects/Geconomicus#37]
Le lien dans l'image du logo, dans le menu de gauche, n'est pas reconnu par firefox (sous Linux)

`src="_static/logo\logo.png"`
au lieu de 
`src="_static/logo/logo.png"`
(antislash au lieu de slash)

et il faut que tu ajoute  width="150px"  sinon l'image est énorme et dépasse du menu

**Comment by galuel** [comment]
A noter quand même que sous Firefox 47.0 / Ubuntu 16.04 ça fonctionne très bien...

**Comment by galuel** [comment]
Résolu... Sphinx 1.3 gère mal le path "logo/logo.png" et aussi le path "logo/logo_favicon.png", le changement par "logo\logo.png" et le positionnement du favicon dans ./static/logo_favicon.png avaient résolu le soucis semble-t-il, mais sphinx générait alors "_static/logo\logo.png" pour le logo, ce qui semble poser soucis...

Solution : les deux images ont été mises directement dans "./_static" en mettant uniquement le nom de l'image dans conf.py : 

`html_logo = 'logo.png'`
`html_favicon = 'logo_favicon.png'`

Il s'agit donc d'un bug de sphinx contourné, en attendant des versions ultérieures...

**Comment by vtexier** [comment]
@galuel : j'ai volontairement bloqué Sphinx à la version 1.3, car la version 1.4 ne contient plus par défaut le thème HTML ReadTheDoc. Il faut l'installer soi-même.

Donc, si tu veux mettre à jour Sphinx en 1.4 via pip, tu peux mais tu dois : 
 installer toi même le thème HTML, via pip aussi, voir https://pypi.python.org/pypi/sphinx_rtd_theme

Et vérifier que tout fonctionne ;)
