### ISSUE TITLE
How make simple thing with sphinx ?

### ISSUE THREAD

**Issue by galuel** [libre-money-projects/Geconomicus#38]
Résumons-nous : Inséré à la main la référence à la dernière release : http://geconomicus.glibre.org/index.html + exemple source : http://geconomicus.glibre.org/latestreleases.html

Comment insérer ça dans les sources pour que sphinx le génère à la fin ? J'ai péniblement trouvé comment insérer du javascript dans le <head> pour le minijappix, ça c'est bon.

Mais là pour que ce soit complet il faut trouver le moyen de faire appel à un tag HTML défini. Quelque chose d'hyper simple à faire en HTML, mais sphinx rajoutant une barrière à l'entrée afin de rendre tout plus compliqué : comment on fait ?

**Comment by galuel** [comment]
Vu le temps passé à chercher sans trouver de solution, il vaut mieux générer le .zip de chaque nouvelle release en **insérant directement à la main dans le HTML généré final le tag ID nécessaire**. Le fichier .js pourra lui être ajouté comme il a été ajouté pour minijappix.

De gros doutes quant à la pertinence d'utiliser un principe aussi lourd pour générer quelques pages HTML. La barrière à l'entrée pour de nouveaux contributeurs me semble tout à fait insurmontable dans cet objectif.

**Comment by vtexier** [comment]
>  insérant directement à la main dans le HTML généré final le tag ID nécessaire

Surtout pas, une release doit toujours correspondre au code source fourni avec.

> De gros doutes quant à la pertinence d'utiliser un principe aussi lourd pour générer quelques pages HTML. La barrière à l'entrée pour de nouveaux contributeurs me semble tout à fait insurmontable dans cet objectif.

Il permet pourtant de : 
* séparer le contenu de la présentation
* intégrer automatiquement un formulaire de recherche
* intégrer une table des matières auto générée
* maintenir des traductions facilement via weblate
* est parfaitement adapté au versionning git
* est parfaitement adapté à une automatisation via travis

Merci de proposer un autre système ayant au moins ces caractéristiques.

**Comment by galuel** [comment]
Pour générer quelques pages HTML ces automatismes ne sont pas nécessaires. Qui plus est la barrière à l'entrée qui nécessite l'apprentissage de tout un langage pour des automatismes de luxe concernant un site HTML très simple est colossale et prive le projet de contributeurs potentiels.

Là où la connaissance du HTML est suffisante, une modification qui prend 30 secondes prend plusieurs heures avec sphinx qui  reste un outil spécifique concernant des applications spécifiques, qui ne sont pas forcément adéquates ici.

En attendant qu'une solution existe pour insérer facilement et sans efforts un tag id dans le HTML généré, il sera effectué l'insert nécessaire à la main dans les versions futures.

Le fait que cet outil très lourd demande une recherche approfondie infructueuses après plusieurs heures passées dessus pour insérer un simple tag HTML sur un site de quelques pages ne va pas dans le sens de sa pertinence pour ce projet spécifique.

**Comment by vtexier** [comment]
Tu peux essayer la directive "raw" : 

The "raw" directive can be used to insert raw HTML into HTML output:

Here is some |stuff|.

```
.. |stuff| raw:: html

   <em>emphasized text containing a
   <a href="http://example.org">hyperlink</a> and
   <tt>inline literals</tt></em>
```

**Comment by vtexier** [comment]
Voilà la solution, cela permet d'ajouter une balise html avec un id sur lequel on peut agir.
Et la note supporte la traduction. CQFD.

```
.. |html_last_version| raw:: html

    <span id="last_version_id">2.x</span>

.. note:: Dernière version disponible |html_last_version|
```

**Comment by galuel** [comment]
Chouette !

**Comment by galuel** [comment]
Résolu en version 2.16
