### ISSUE TITLE
Correction dans le fichier geconomicus_money.ods

### ISSUE THREAD

**Issue by fbuland** [libre-money-projects/Geconomicus#41]
Bonjour,
J'ai détecté une petite boulette dans le fichier geconomicus_money.ods (que j'ai téléchargé depuis http://geconomicus.glibre.org/rules.html#compte-rendu), pour le calcul de l'écart-type avec la banque (2ème graphique après celui sans la banque). L'impact est la ligne jaune de l'écart-type qui n'est pas correct.
Onglet Monnaie-dette, colonnes X4 à X15, la formule n'est pas correcte :
=ECARTYPE($R$4;$R$15)/W4
Entre les 2 variables de l'écart-type, il faut remplacer le ";" par un ":"

La version corrigée :
[geconomicus_money - fixed.zip](https://github.com/libre-money-projects/Geconomicus/files/659361/geconomicus_money.-.fixed.zip)

Franck

**Comment by galuel** [comment]
Corrigé dans la [release 2.18](http://geconomicus.glibre.org/) génération manuelle française uniquement [disponible ici pour déploiement](https://github.com/libre-money-projects/Geconomicus/tree/2.18).
